fetchInterval: "10s"
sources:
  - title: Microsiervos
    shortName: microsiervos
    homepage: https://www.microsiervos.com
    rss: https://www.microsiervos.com/index.xml
    withChannels: true

  - title: Wired
    shortName: wired
    homepage: https://wired.com
    rss: https://www.wired.com/feed/rss
    withChannels: true

  - title: The Verge
    shortName: verge
    homepage: https://www.theverge.com/
    rss: https://www.theverge.com/rss/index.xml
    withChannels: false

  - title: Gizmodo
    shortName: gizmodo
    homepage: https://es.gizmodo.com
    rss: https://es.gizmodo.com/rss
    withChannels: true

  - title: Hacker News
    shortName: hackernews
    homepage: https://news.ycombinator.com
    rss: https://hnrss.org/frontpage
    withChannels: true

  - title: The New York Times
    shortName: nytimes
    homepage: https://nytimes.com
    rss: https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/technology/rss.xml
    withChannels: true
